import json
import os

vi_path = "E:/CNWeb_git/projectCKCNW/resources/lang/vi.json"
en_path = "E:/CNWeb_git/projectCKCNW/resources/lang/en.json"

new_vi_keys = {
    "Đăng Nhập Tài Khoản": "Đăng Nhập Tài Khoản",
    "Đăng nhập để tiếp tục học tập": "Đăng nhập để tiếp tục học tập",
    "Email": "Email",
    "Mật Khẩu": "Mật Khẩu",
    "Nhập mật khẩu": "Nhập mật khẩu",
    "Ghi nhớ tôi": "Ghi nhớ tôi",
    "Chưa có tài khoản?": "Chưa có tài khoản?",
    "Tài khoản demo:": "Tài khoản demo:",
    "Đăng Kí Tài Khoản": "Đăng Kí Tài Khoản",
    "Tham gia nền tảng học tập trực tuyến": "Tham gia nền tảng học tập trực tuyến",
    "Họ và Tên": "Họ và Tên",
    "Nhập họ và tên": "Nhập họ và tên",
    "Ít nhất 6 ký tự": "Ít nhất 6 ký tự",
    "Xác Nhận Mật Khẩu": "Xác Nhận Mật Khẩu",
    "Nhập lại mật khẩu": "Nhập lại mật khẩu",
    "Bạn là ai?": "Bạn là ai?",
    "Đã có tài khoản?": "Đã có tài khoản?",
    "Bảng Điều Khiển": "Bảng Điều Khiển",
    "Xem lớp học, khóa học và điểm số của bạn": "Xem lớp học, khóa học và điểm số của bạn",
    "Bạn đang đăng nhập với tư cách": "Bạn đang đăng nhập với tư cách",
    "Lớp (Duyệt)": "Lớp (Duyệt)",
    "Chờ Duyệt": "Chờ Duyệt",
    "Khóa Học": "Khóa Học",
    "Điểm TB": "Điểm TB",
    "Tham gia lớp & khóa học": "Tham gia lớp & khóa học",
    "Nhập mã lớp hoặc chọn khóa học phù hợp": "Nhập mã lớp hoặc chọn khóa học phù hợp",
    "Tham gia lớp học": "Tham gia lớp học",
    "Lớp Học Của Bạn": "Lớp Học Của Bạn",
    "Không có mô tả": "Không có mô tả",
    "Xem chi tiết →": "Xem chi tiết →",
    "Yêu Cầu Tham Gia Chờ Duyệt": "Yêu Cầu Tham Gia Chờ Duyệt",
    "Chờ duyệt...": "Chờ duyệt...",
    "Lớp:": "Lớp:",
    "Quản lý lớp học, học sinh và phòng học trực tuyến": "Quản lý lớp học, học sinh và phòng học trực tuyến",
    "Mã lớp:": "Mã lớp:",
    "Quản lý lớp & khóa học": "Quản lý lớp & khóa học",
    "Bạn chưa tạo lớp học nào": "Bạn chưa tạo lớp học nào",
    "+ Tạo lớp mới": "+ Tạo lớp mới",
    "Tạo lớp học nhanh": "Tạo lớp học nhanh",
    "Tên lớp học": "Tên lớp học",
    "Tạo lớp": "Tạo lớp",
    "Lỗi!": "Lỗi!",
    "Giáo Viên": "Giáo Viên",
    "Học Sinh": "Học Sinh",
    "Đăng Nhập": "Đăng Nhập",
    "Sửa thông tin": "Sửa thông tin",
    "Thông tin cá nhân": "Thông tin cá nhân",
    "Email cá nhân": "Email cá nhân",
    "Hồ sơ của tôi": "Hồ sơ của tôi",
    "Học sinh": "Học sinh",
    "Giáo viên": "Giáo viên",
    "Người dùng": "Người dùng",
    "Khác": "Khác",
    "Thông tin cơ bản": "Thông tin cơ bản",
    "Tên:": "Tên:",
    "Email (TK):": "Email (TK):",
    "Vai trò:": "Vai trò:",
    "Lớp đã tham gia": "Lớp đã tham gia",
    "Mã:": "Mã:",
    "Xem": "Xem",
    "Chưa tham gia lớp nào": "Chưa tham gia lớp nào",
    "Khóa học đã tham gia": "Khóa học đã tham gia",
    "Chưa tham gia khóa học nào": "Chưa tham gia khóa học nào",
    "Lớp đang quản lý": "Lớp đang quản lý",
    "Chưa có lớp quản lý": "Chưa có lớp quản lý",
    "Khóa học": "Khóa học",
    "Chưa có khóa học nào": "Chưa có khóa học nào",
    "Chỉnh sửa thông tin": "Chỉnh sửa thông tin",
    "Tên": "Tên",
    "Email": "Email",
    "Mật khẩu mới (để trống nếu không đổi)": "Mật khẩu mới (để trống nếu không đổi)",
    "Xác nhận mật khẩu": "Xác nhận mật khẩu",
    "Lưu thay đổi": "Lưu thay đổi",
    "Hủy": "Hủy",
    "Chi tiết khóa học": "Chi tiết khóa học",
    "← Quay lại lớp học": "← Quay lại lớp học",
    "Giáo viên:": "Giáo viên:",
    "Mô Tả": "Mô Tả",
    "Số Phòng Học": "Số Phòng Học",
    "Số Học Sinh Trong Khóa": "Số Học Sinh Trong Khóa",
    "Bạn chưa tham gia khóa học này. Hãy tham gia để xem thêm thông tin.": "Bạn chưa tham gia khóa học này. Hãy tham gia để xem thêm thông tin.",
    "Tham gia khóa học": "Tham gia khóa học",
    "Phòng Học": "Phòng Học",
    "Vào phòng →": "Vào phòng →",
    "Khóa học này chưa có phòng học nào được lên lịch.": "Khóa học này chưa có phòng học nào được lên lịch.",
    "Danh Sách Học Sinh Trong Khóa": "Danh Sách Học Sinh Trong Khóa",
    "Khóa học này chưa có học sinh nào tham gia.": "Khóa học này chưa có học sinh nào tham gia.",
    "Bài Tập": "Bài Tập",
    "Hạn:": "Hạn:",
    "Đã hết hạn": "Đã hết hạn",
    "Điểm:": "Điểm:",
    "Xem bài làm →": "Xem bài làm →",
    "Bài tập đã kết thúc! Bạn không thể làm bài này nữa.": "Bài tập đã kết thúc! Bạn không thể làm bài này nữa.",
    "Bài tập đã kết thúc ✕": "Bài tập đã kết thúc ✕",
    "Làm bài →": "Làm bài →",
    "Khóa học này chưa có bài tập.": "Khóa học này chưa có bài tập.",
    "Bài Kiểm Tra": "Bài Kiểm Tra",
    "Bài kiểm tra đã kết thúc! Bạn không thể làm bài này nữa.": "Bài kiểm tra đã kết thúc! Bạn không thể làm bài này nữa.",
    "Bài kiểm tra đã kết thúc ✕": "Bài kiểm tra đã kết thúc ✕",
    "Khóa học này chưa có bài kiểm tra.": "Khóa học này chưa có bài kiểm tra.",
    "Bạn chắc chắn muốn rời khỏi khóa học này?": "Bạn chắc chắn muốn rời khỏi khóa học này?",
    "Rời khỏi khóa học": "Rời khỏi khóa học",
    "Thông tin học sinh": "Thông tin học sinh",
    "Xem thông tin": "Xem thông tin",
    "bảng điểm": "bảng điểm",
    "Điểm thi trung bình": "Điểm thi trung bình",
    "Bảng Điểm Thi / Bài Tập": "Bảng Điểm Thi / Bài Tập",
    "Bài tập/Bài kiểm tra": "Bài tập/Bài kiểm tra",
    "Điểm": "Điểm",
    "Lịch Sử": "Lịch Sử",
    "Lịch sử làm bài→": "Lịch sử làm bài→",
    "Chưa có thông tin điểm số.": "Chưa có thông tin điểm số.",
    "Tạo khóa học / phòng học": "Tạo khóa học / phòng học",
    "Tạo bài tập / bài kiểm tra": "Tạo bài tập / bài kiểm tra",
    "Quản lý bài tập / bài kiểm tra": "Quản lý bài tập / bài kiểm tra",
    "Quản lý": "Quản lý",
    "Lớp Học": "Lớp học",
    "Tạo và quản lý lớp học của bạn": "Tạo và quản lý lớp học của bạn",
    "Xem chi tiết": "Xem chi tiết",
    "Xóa lớp": "Xóa lớp",
    "Sinh viên": "Sinh viên",
    "Khóa học": "Khóa học",
    "Phòng học": "Phòng học",
    "Sinh viên chờ duyệt": "Sinh viên chờ duyệt",
    "Duyệt": "Duyệt",
    "Không có sinh viên chờ duyệt.": "Không có sinh viên chờ duyệt.",
    "Bạn chưa tạo khóa học nào": "Bạn chưa tạo khóa học nào",
    "Bấm Xem chi tiết để hiện phần tạo khóa học, phòng học và bài tập.": "Bấm Xem chi tiết để hiện phần tạo khóa học, phòng học và bài tập.",
    "← Quay lại": "← Quay lại",
    "Giáo viên": "Giáo viên",
    "Giáo viên phụ trách": "Giáo viên phụ trách",
    "Học sinh trong lớp": "Học sinh trong lớp",
    "Mã Lớp": "Mã Lớp",
    "Số Sinh Viên": "Số Sinh Viên",
    "Số Khóa Học": "Số Khóa Học",
    "Khóa Học Trong Lớp": "Khóa Học Trong Lớp",
}

new_en_keys = {
    "Đăng Nhập Tài Khoản": "Login to Account",
    "Đăng nhập để tiếp tục học tập": "Log in to continue learning",
    "Email": "Email",
    "Mật Khẩu": "Password",
    "Nhập mật khẩu": "Enter password",
    "Ghi nhớ tôi": "Remember me",
    "Chưa có tài khoản?": "Don't have an account?",
    "Tài khoản demo:": "Demo accounts:",
    "Đăng Kí Tài Khoản": "Register Account",
    "Tham gia nền tảng học tập trực tuyến": "Join the online learning platform",
    "Họ và Tên": "Full Name",
    "Nhập họ và tên": "Enter your full name",
    "Ít nhất 6 ký tự": "At least 6 characters",
    "Xác Nhận Mật Khẩu": "Confirm Password",
    "Nhập lại mật khẩu": "Re-enter password",
    "Bạn là ai?": "Who are you?",
    "Đã có tài khoản?": "Already have an account?",
    "Bảng Điều Khiển": "Dashboard",
    "Xem lớp học, khóa học và điểm số của bạn": "View your classes, courses, and grades",
    "Bạn đang đăng nhập với tư cách": "You are logged in as",
    "Lớp (Duyệt)": "Classes (Approved)",
    "Chờ Duyệt": "Pending Approval",
    "Khóa Học": "Courses",
    "Điểm TB": "Avg Score",
    "Tham gia lớp & khóa học": "Join classes & courses",
    "Nhập mã lớp hoặc chọn khóa học phù hợp": "Enter class code or select a suitable course",
    "Tham gia lớp học": "Join class",
    "Lớp Học Của Bạn": "Your Classes",
    "Không có mô tả": "No description",
    "Xem chi tiết →": "View details →",
    "Yêu Cầu Tham Gia Chờ Duyệt": "Pending Join Requests",
    "Chờ duyệt...": "Pending...",
    "Lớp:": "Class:",
    "Quản lý lớp học, học sinh và phòng học trực tuyến": "Manage classes, students, and online rooms",
    "Mã lớp:": "Class code:",
    "Quản lý lớp & khóa học": "Manage classes & courses",
    "Bạn chưa tạo lớp học nào": "You haven't created any classes yet",
    "+ Tạo lớp mới": "+ Create new class",
    "Tạo lớp học nhanh": "Quickly create a class",
    "Tên lớp học": "Class name",
    "Tạo lớp": "Create class",
    "Lỗi!": "Error!",
    "Giáo Viên": "Teacher",
    "Học Sinh": "Student",
    "Đăng Nhập": "Login",
    "Đăng Kí": "Register",
    "Thoát":"Exit",
    "Tài Khoản": "Account",
    "Sửa thông tin": "Edit Info",
    "Thông tin cá nhân": "Personal Information",
    "Email cá nhân": "Personal Email",
    "Hồ sơ của tôi": "My Profile",
    "Học sinh": "Student",
    "Giáo viên": "Teacher",
    "Người dùng": "User",
    "Khác": "Other",
    "Thông tin cơ bản": "Basic Information",
    "Tên:": "Name:",
    "Email (TK):": "Email (Account):",
    "Vai trò:": "Role:",
    "Lớp đã tham gia": "Joined Classes",
    "Mã:": "Code:",
    "Xem": "View",
    "Chưa tham gia lớp nào": "No classes joined",
    "Khóa học đã tham gia": "Joined Courses",
    "Chưa tham gia khóa học nào": "No courses joined",
    "Lớp đang quản lý": "Managing Classes",
    "Chưa có lớp quản lý": "No classes to manage",
    "Khóa học": "Courses",
    "Chưa có khóa học nào": "No courses available",
    "Chỉnh sửa thông tin": "Edit Information",
    "Tên": "Name",
    "Mật khẩu mới (để trống nếu không đổi)": "New password (leave blank if unchanged)",
    "Xác nhận mật khẩu": "Confirm password",
    "Lưu thay đổi": "Save changes",
    "Hủy": "Cancel",
    "Chi tiết khóa học": "Course Details",
    "← Quay lại lớp học": "← Back to Class",
    "Giáo viên:": "Teacher:",
    "Mô Tả": "Description",
    "Số Phòng Học": "Number of Rooms",
    "Số Học Sinh Trong Khóa": "Number of Students in Course",
    "Bạn chưa tham gia khóa học này. Hãy tham gia để xem thêm thông tin.": "You haven't joined this course yet. Join to see more information.",
    "Tham gia khóa học": "Join Course",
    "Phòng Học": "Rooms",
    "Vào phòng →": "Enter room →",
    "Khóa học này chưa có phòng học nào được lên lịch.": "This course has no scheduled rooms yet.",
    "Danh Sách Học Sinh Trong Khóa": "Student List in Course",
    "Khóa học này chưa có học sinh nào tham gia.": "No students have joined this course yet.",
    "Bài Tập": "Assignments",
    "Hạn:": "Deadline:",
    "Đã hết hạn": "Expired",
    "Điểm:": "Score:",
    "Xem bài làm →": "View submission →",
    "Bài tập đã kết thúc! Bạn không thể làm bài này nữa.": "Assignment ended! You can no longer submit.",
    "Bài tập đã kết thúc ✕": "Assignment ended ✕",
    "Làm bài →": "Do assignment →",
    "Khóa học này chưa có bài tập.": "This course has no assignments.",
    "Bài Kiểm Tra": "Quizzes",
    "Bài kiểm tra đã kết thúc! Bạn không thể làm bài này nữa.": "Quiz ended! You can no longer submit.",
    "Bài kiểm tra đã kết thúc ✕": "Quiz ended ✕",
    "Khóa học này chưa có bài kiểm tra.": "This course has no quizzes.",
    "Bạn chắc chắn muốn rời khỏi khóa học này?": "Are you sure you want to leave this course?",
    "Rời khỏi khóa học": "Leave Course",
    "Tạo khóa học / phòng học": "Create Course / Room",
    "Tạo bài tập / bài kiểm tra": "Create Assignment / Quiz",
    "Quản lý bài tập / bài kiểm tra": "Manage Assignment / Quiz",
    "Quản lý": "Manage",
    "Lớp Học": "Classroom",
    "Tạo và quản lý lớp học của bạn": "Create and manage your classes",
    "Xem chi tiết": "View details",
    "Xóa lớp": "Delete class",
    "Sinh viên": "Student",
    "Khóa học": "Course",
    "Phòng học": "Room",
    "Sinh viên chờ duyệt": "Pending Students",
    "Duyệt": "Approve",
    "Không có sinh viên chờ duyệt.": "No pending students.",
    "Bạn chưa tạo khóa học nào": "You haven't created any courses yet",
    "Bấm Xem chi tiết để hiện phần tạo khóa học, phòng học và bài tập.": "Click View details to show the course creation, room, and assignment sections.",
    "← Quay lại": "← Back",
    "Giáo viên": "Teacher",
    "Giáo viên phụ trách": "In-charge Teacher",
    "Học sinh trong lớp": "Students in Class",
    "Mã Lớp": "Class Code",
    "Số Sinh Viên": "Number of Students",
    "Số Khóa Học": "Number of Courses",
    "Khóa Học Trong Lớp": "Courses in Class",
    "Danh Sách Học Sinh Trong Lớp": "Student List in Class",
    "Tham gia khóa học": "Join Course",
    "Rời khỏi lớp học": "Leave Class",
    "Xem chi tiết": "View details",
    "Bấm để xem bài tập và bài kiểm tra": "Click to view assignments and quizzes",
    "Tạo khóa học": "Create Course",
    "Tạo phòng học": "Create Room",
    "Tạo bài tập": "Create Assignment",
    "Tạo bài kiểm tra": "Create Quiz",
    "Tên khóa học": "Course Name",
    "Mô tả (tùy chọn)": "Description (optional)",
    "Bạn muốn tạo gì?": "What do you want to create?",
    "Tên phòng học": "Room Name",
    "Thời lượng(phút)": "Time (minutes)",
    "Source Bài tập / Bài kiểm tra": "Assignment / Quiz Source",
    "Loại:": "Type",
    "Khóa học:": "Course",
    "Bài tập": "Assignment",
    "Bài kiểm tra": "Quiz",
    "Đăng lại": "Repost",
    "Sửa": "Edit",
    "Chỉnh sửa thông tin cá nhân": "Edit Personal Information",
    "Tham gia": "Join",
    "Tham gia Lớp & Khóa học": "Join Classes & Courses",
    "Nhập mã lớp để tham gia hoặc chọn khóa học từ lớp đã tham gia": "Enter class code to join or select course from joined classes",
    "Tham gia lớp mới": "Join new class",
    "Nhập mã lớp": "Enter class code",
    "Tham gia lớp": "Join class",
    "Lớp học khác": "Other Classes",
    "Tham gia": "Join",
    "Lớp học của bạn": "Your Classes",
    "Rời khỏi lớp": "Leave Class",
    "Khóa học có sẵn": "Available Courses",
    "Rời khỏi": "Leave",
}

# Update vi.json
if os.path.exists(vi_path):
    with open(vi_path, 'r', encoding='utf-8') as f:
        vi_data = json.load(f)
else:
    vi_data = {}
    
vi_data.update(new_vi_keys)
with open(vi_path, 'w', encoding='utf-8') as f:
    json.dump(vi_data, f, ensure_ascii=False, indent=4)

# Update en.json
if os.path.exists(en_path):
    with open(en_path, 'r', encoding='utf-8') as f:
        en_data = json.load(f)
else:
    en_data = {}
    
en_data.update(new_en_keys)
with open(en_path, 'w', encoding='utf-8') as f:
    json.dump(en_data, f, ensure_ascii=False, indent=4)

print("Translations updated successfully.")
